### ISSUE TITLE
Aurelia path 1.1.2 is a breaking change (and therefore should be a higher version bump)

### ISSUE THREAD

**Issue by svenvandescheur** [aurelia/path#29]
**I'm submitting a bug report**

* **Library Version:**
1.1.2

* **Operating System:**
OSX 10.14.2

* **Node Version:**
11.4.0

* **NPM Version:**
6.5.0

* **JSPM OR Webpack AND Version**
webpack 4.16.2

* **Browser:**
IE 11 

* **Language:**
ESNext

**Current behavior:**

IE11 crashes on a syntax error caused by leaking ESNext statements.

Webpack supports both `module` as `main` as resolver and is, in many cases configured (due to performance) to ignore babel transpilation for "node_modules". Because of this many packages (including aurelia-path) ship transpiled versions listed in the `main` section of package.json.

Aurelia-path 1.1.2 [adds a `module` key](https://github.com/aurelia/path/commit/7466b01dc72a3b09da0e8481cfe896cf72dba80f) to package.json to supply an alternative es2015 build.

Webpack, by default, is configured to load resolve both `module` and `main` but the first has the highest priority. This means that previous aurelia-path 1.1.1 (e.g. as dependency of aurelia-http-client) worked fine in a webpack+babel environment, but 1.1.2 leaked ESNext code into the bundle introducing breaking changes. I noticed this as a package depending on aurelia-http-client started (depending on aurelia-path) [started failing on IE11](https://travis-ci.org/maykinmedia/consumerjs/builds/481438539)

* **What is the expected behavior?**

The behaviour I expect is either a non-breaking change or a major version bump leading to a clean migration path without any failing builds on existing packages/implementations. I can see the benefit of adding `module` in package.json but dealing with this requires work from the user's end. 

* **What is the motivation / use case for changing the behavior?**

Semver is intended to avoid conflicts in upgraded between package. [NPM's versioning system](https://docs.npmjs.com/misc/semver) is designed to deal with this and will, automatically resolve the best suitable working version based on its version definition listed in package.json. Because 1.1.2 was listed as a patch release. NPM thinks it's OK to use it as dependency for aurelia-http-client where it actually introduced breaking changes for a lot of environments.

**Comment by bigopon** [comment]
@svenvandescheur Thanks for filing this, it seems you are using webpack, which should be helped by our AureliaPlugin to select `native-modules` to avoid this issue, but maybe I understood it wrong. @jods4 Could you please help give some input?

**Comment by jods4** [comment]
@bigopon As I understand it, there's one issue and there are possible workarounds.

An added `module` key in `package.json` will be picked up by Webpack before `main`. The rationale here is that `module` should point to a standard ES module file format, which is much better input than AMD, CommonJS and co.

Unrelated to that is the ES version of code in `main` and `module` files. If `main` is **ES3**, then hiding it with a `module` file that is **ES5** is indeed a breaking change for users that don't transpile libraries (most users) and that target non-ES5 browsers (fewer and fewer thankfully).

A non-breaking change would have been to put our `native-modules` distribution in `module` rather than `es2015`. The former is ES3 code inside a standard module, the latter is fully ES2015.

Now the work-around:
This _should_ be mostly irrelevant when using `AureliaPlugin` because by default it switches distribution to `native-modules` anyway (configurable through `dist` option). I can only assume that this issue arises when _not_ using the plugin.

Side-note: the part that redirects distributions is usable independently from the full plugin. `DistPlugin` does the path rewriting, it's exported by `aurelia-webpack-plugin` and can be used "stand-alone".

**Comment by bigopon** [comment]
@jods4 Thanks for the input here. It seems the effect on non Aurelia app was not considered carefully. I apologize for this @svenvandescheur and any one affected. I didn't do those PRs with enough care in mind.

@EisenbergEffect @jods4  What do you think we should do? Revert the changes? It only affects Aurelia-script, which I can easily create an alias.

**Comment by huochunpeng** [comment]
Something does not sound right.

As @jods4 said, our aurelia-webpack-plugin always picks `dist/native-modules` folder (if it exsits) over `module`/`main`/`browser` fields in `package.json`.

That is turned on by default. Unless you explicitly turn it off.

https://github.com/aurelia/webpack-plugin/blob/274373028f8c4d86d1abc08a97210c2dc961f96a/src/AureliaPlugin.ts#L48

That's why all other aurelia-* package new `module` (es2015) field didn't break any app. Why is this one different? @svenvandescheur can you share your webpack.config file?

**Comment by huochunpeng** [comment]
I am guessing @svenvandescheur is not using aurelia-path in an aurelia app.

aurelia-path itself is generic, as well as many other aurelia core packages.

@bigopon we talked about this before, the safest way is to use `module` to point to `native-modules` not `es2015` for browser compatibility. For instance, people may use aurelia-dependency-injection in non-aurelia apps.

**Comment by svenvandescheur** [comment]
@huochunpeng I'm not using aurelia-webpack-plugin but relying on auralia-http-client for a REST library. This library can be installed using nom and be further processes by any bundler (lik Webpack) on actual projects.

What happened here is that the actual project uses the REST library (which installed aurelia-http-client, and so aurelia-path). This was bundled using a pretty default Webpack configuration picking up the ESNext module of aurelia path after 1.1.2 was released resulting in breaking changes for existing environments.

We have multiple projects with this setup, as well as others (unknown parties) that may rely on the library in a similar way which are now very likely to be be also broken.

**Comment by huochunpeng** [comment]
@svenvandescheur for short term fix, you can skip `module` field in webpack config.

https://webpack.js.org/configuration/resolve/#resolve-mainfields

```js
module.exports = {
  //...
  resolve: {
    mainFields: ['browser', /* 'module', */ 'main']
  }
};
```

Most Aurelia packages will end up using commonjs (main) build.

**Comment by EisenbergEffect** [comment]
@svenvandescheur We're also working on a long term fix and we apologize for the trouble this has caused you.

**Comment by svenvandescheur** [comment]
@huochunpeng @EisenbergEffect 

Thanks for the update, in the mean time reconfiguring Webpack Is a working workaround. I appreciate you working on a long term fix.

**Comment by 3cp** [comment]
@svenvandescheur latest release fixed this issue.
